<?php
/**
 * OrganizationsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  WebMI\KeycloakApiClient\KeycloakApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Keycloak Admin REST API
 *
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace WebMI\KeycloakApiClient\KeycloakApi\Test\Api;

use \WebMI\KeycloakApiClient\KeycloakApi\Configuration;
use \WebMI\KeycloakApiClient\KeycloakApi\ApiException;
use \WebMI\KeycloakApiClient\KeycloakApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrganizationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  WebMI\KeycloakApiClient\KeycloakApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrganizationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for adminRealmsRealmOrganizationsGet
     *
     * Returns a paginated list of organizations filtered according to the specified parameters.
     *
     */
    public function testAdminRealmsRealmOrganizationsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdDelete
     *
     * Deletes the organization.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdGet
     *
     * Returns the organization representation.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdIdentityProvidersAliasDelete
     *
     * Removes the identity provider with the specified alias from the organization.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdIdentityProvidersAliasDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdIdentityProvidersAliasGet
     *
     * Returns the identity provider associated with the organization that has the specified alias.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdIdentityProvidersAliasGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdIdentityProvidersGet
     *
     * Returns all identity providers associated with the organization.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdIdentityProvidersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdIdentityProvidersPost
     *
     * Adds the identity provider with the specified id to the organization.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdIdentityProvidersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdMembersCountGet
     *
     * Returns number of members in the organization..
     *
     */
    public function testAdminRealmsRealmOrganizationsIdMembersCountGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdMembersGet
     *
     * Returns a paginated list of organization members filtered according to the specified parameters.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdMembersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdMembersIdDelete
     *
     * Removes the user with the specified id from the organization.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdMembersIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdMembersIdGet
     *
     * Returns the member of the organization with the specified id.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdMembersIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdMembersIdOrganizationsGet
     *
     * Returns the organizations associated with the user that has the specified id.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdMembersIdOrganizationsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdMembersInviteExistingUserPost
     *
     * Invites an existing user to the organization, using the specified user id.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdMembersInviteExistingUserPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdMembersInviteUserPost
     *
     * Invites an existing user or sends a registration link to a new user, based on the provided e-mail address..
     *
     */
    public function testAdminRealmsRealmOrganizationsIdMembersInviteUserPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdMembersPost
     *
     * Adds the user with the specified id as a member of the organization.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdMembersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsIdPut
     *
     * Updates the organization.
     *
     */
    public function testAdminRealmsRealmOrganizationsIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsMembersIdOrganizationsGet
     *
     * Returns the organizations associated with the user that has the specified id.
     *
     */
    public function testAdminRealmsRealmOrganizationsMembersIdOrganizationsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminRealmsRealmOrganizationsPost
     *
     * Creates a new organization.
     *
     */
    public function testAdminRealmsRealmOrganizationsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
