<?php
/**
 * RealmsRealmProtocolOpenidConnectTokenPost200ResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WebMI\KeycloakApiClient\CustomApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Keycloak Rest API
 *
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace WebMI\KeycloakApiClient\CustomApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RealmsRealmProtocolOpenidConnectTokenPost200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description RealmsRealmProtocolOpenidConnectTokenPost200Response
 * @package     WebMI\KeycloakApiClient\CustomApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RealmsRealmProtocolOpenidConnectTokenPost200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RealmsRealmProtocolOpenidConnectTokenPost200Response"
     */
    public function testRealmsRealmProtocolOpenidConnectTokenPost200Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "access_token"
     */
    public function testPropertyAccessToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expires_in"
     */
    public function testPropertyExpiresIn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "refresh_expires_in"
     */
    public function testPropertyRefreshExpiresIn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "refresh_token"
     */
    public function testPropertyRefreshToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "token_type"
     */
    public function testPropertyTokenType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "not_before_policy"
     */
    public function testPropertyNotBeforePolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "session_state"
     */
    public function testPropertySessionState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "scope"
     */
    public function testPropertyScope()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
