<?php
/**
 * UnmanagedAttributePolicy
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WebMI\KeycloakApiClient\KeycloakApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Keycloak Admin REST API
 *
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WebMI\KeycloakApiClient\KeycloakApi\Model;
use \WebMI\KeycloakApiClient\KeycloakApi\ObjectSerializer;

/**
 * UnmanagedAttributePolicy Class Doc Comment
 *
 * @category Class
 * @package  WebMI\KeycloakApiClient\KeycloakApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UnmanagedAttributePolicy
{
    /**
     * Possible values of this enum
     */
    public const ENABLED = 'ENABLED';

    public const ADMIN_VIEW = 'ADMIN_VIEW';

    public const ADMIN_EDIT = 'ADMIN_EDIT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ENABLED,
            self::ADMIN_VIEW,
            self::ADMIN_EDIT
        ];
    }
}


