name: OpenApi Client Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build API Clients
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Commented because it was generated locally with a fixed version of openapi generator

      ## Tmp local command: docker run --rm -v "${PWD}:/local" openapi-generator:snake_case generate -g php -o /local/KeycloakApi -i https://www.keycloak.org/docs-api/latest/rest-api/openapi.yaml --skip-validate-spec --additional-properties invokerPackage=WebMI\\KeycloakApiClient\\KeycloakApi,methodNamingConvention=snake_case
      #- name: Generate Authentication API
      #  uses: openapi-generators/openapitools-generator-action@v1
      #  with:
      #    generator: php
      #    openapi-url: https://www.keycloak.org/docs-api/latest/rest-api/openapi.yaml
      #    command-args: --skip-validate-spec --additional-properties invokerPackage="WebMI\\\\KeycloakApiClient\\\\KeycloakApi",methodNamingConvention=snake_case -o ./KeycloakApi

      ## Tmp local command: docker run --rm -v "${PWD}:/local" openapi-generator:snake_case generate -g php -o /local/CustomApi -i /local/custom.yaml --skip-validate-spec --additional-properties invokerPackage=WebMI\\KeycloakApiClient\\CustomApi,methodNamingConvention=snake_case
      #- name: Generate Custom API
      #  uses: openapi-generators/openapitools-generator-action@v1
      #  with:
      #    generator: php
      #    openapi-file: './custom.yaml'
      #    command-args: --skip-validate-spec --additional-properties invokerPackage="WebMI\\\\KeycloakApiClient\\\\CustomApi",methodNamingConvention=snake_case -o ./CustomApi
      
      #- name: Commit APIs
      #  run: |
      #    git add .
      #    git config --global user.name 'Web-MI'
      #    git config --global user.email 'info@web-mi.de'
      #    git commit -am "Updated APIs"
      #    git push
