name: OpenApi Client Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build API Clients
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Authentication API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://www.keycloak.org/docs-api/latest/rest-api/openapi.yaml
          command-args: --skip-validate-spec --additional-properties invokerPackage="WebMI\\\\KeycloakApiClient\\\\KeycloakApi" -o ./KeycloakApi
      - name: Commit APIs
        run: |
          git add .
          git config --global user.name 'Web-MI'
          git config --global user.email 'info@web-mi.de'
          git commit -am "Updated APIs"
          git push
